/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingStatus = IDL.Variant({
  'rented' : IDL.Null,
  'sold' : IDL.Null,
  'available' : IDL.Null,
  'temporarilyUnavailable' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'studio' : IDL.Null,
  'house' : IDL.Null,
  'other' : IDL.Null,
  'land' : IDL.Null,
  'apartment' : IDL.Null,
});
export const Time = IDL.Int;
export const ListingType = IDL.Variant({
  'rent' : IDL.Null,
  'sale' : IDL.Null,
});
export const Address = IDL.Record({
  'street' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'neighborhood' : IDL.Opt(IDL.Text),
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'listingType' : ListingType,
  'updatedAt' : Time,
  'currency' : IDL.Text,
  'address' : Address,
  'areaSqm' : IDL.Nat,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InquiryStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'requester' : IDL.Principal,
  'endDate' : IDL.Text,
  'listingId' : IDL.Nat,
  'createdAt' : Time,
  'updatedAt' : Time,
  'message' : IDL.Text,
  'startDate' : IDL.Text,
});
export const ListingFilters = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'city' : IDL.Opt(IDL.Text),
  'minBedrooms' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'listingType' : IDL.Opt(ListingType),
  'searchText' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const ListingsResult = IDL.Record({
  'listings' : IDL.Vec(Listing),
  'totalCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'create_inquiry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'create_listing' : IDL.Func([Listing], [IDL.Nat], []),
  'delete_listing' : IDL.Func([IDL.Nat], [], []),
  'getAllAvailableListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getListingInquiries' : IDL.Func([IDL.Nat], [IDL.Vec(Inquiry)], ['query']),
  'getListings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(ListingFilters)],
      [ListingsResult],
      ['query'],
    ),
  'getUserInquiries' : IDL.Func([IDL.Principal], [IDL.Vec(Inquiry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'update_inquiry' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
  'update_listing' : IDL.Func([IDL.Nat, Listing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingStatus = IDL.Variant({
    'rented' : IDL.Null,
    'sold' : IDL.Null,
    'available' : IDL.Null,
    'temporarilyUnavailable' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'studio' : IDL.Null,
    'house' : IDL.Null,
    'other' : IDL.Null,
    'land' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const Time = IDL.Int;
  const ListingType = IDL.Variant({ 'rent' : IDL.Null, 'sale' : IDL.Null });
  const Address = IDL.Record({
    'street' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'neighborhood' : IDL.Opt(IDL.Text),
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'listingType' : ListingType,
    'updatedAt' : Time,
    'currency' : IDL.Text,
    'address' : Address,
    'areaSqm' : IDL.Nat,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InquiryStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'requester' : IDL.Principal,
    'endDate' : IDL.Text,
    'listingId' : IDL.Nat,
    'createdAt' : Time,
    'updatedAt' : Time,
    'message' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const ListingFilters = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'city' : IDL.Opt(IDL.Text),
    'minBedrooms' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'listingType' : IDL.Opt(ListingType),
    'searchText' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const ListingsResult = IDL.Record({
    'listings' : IDL.Vec(Listing),
    'totalCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'create_inquiry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'create_listing' : IDL.Func([Listing], [IDL.Nat], []),
    'delete_listing' : IDL.Func([IDL.Nat], [], []),
    'getAllAvailableListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getListingInquiries' : IDL.Func([IDL.Nat], [IDL.Vec(Inquiry)], ['query']),
    'getListings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(ListingFilters)],
        [ListingsResult],
        ['query'],
      ),
    'getUserInquiries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'update_inquiry' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
    'update_listing' : IDL.Func([IDL.Nat, Listing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };