/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : [] | [string],
  'city' : string,
  'neighborhood' : [] | [string],
}
export interface Inquiry {
  'id' : bigint,
  'status' : InquiryStatus,
  'requester' : Principal,
  'endDate' : string,
  'listingId' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'message' : string,
  'startDate' : string,
}
export type InquiryStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'description' : string,
  'amenities' : Array<string>,
  'listingType' : ListingType,
  'updatedAt' : Time,
  'currency' : string,
  'address' : Address,
  'areaSqm' : bigint,
  'bathrooms' : bigint,
  'price' : bigint,
  'photos' : Array<string>,
}
export interface ListingFilters {
  'propertyType' : [] | [PropertyType],
  'city' : [] | [string],
  'minBedrooms' : [] | [bigint],
  'maxPrice' : [] | [bigint],
  'listingType' : [] | [ListingType],
  'searchText' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ListingStatus = { 'rented' : null } |
  { 'sold' : null } |
  { 'available' : null } |
  { 'temporarilyUnavailable' : null };
export type ListingType = { 'rent' : null } |
  { 'sale' : null };
export interface ListingsResult {
  'listings' : Array<Listing>,
  'totalCount' : bigint,
}
export type PropertyType = { 'studio' : null } |
  { 'house' : null } |
  { 'other' : null } |
  { 'land' : null } |
  { 'apartment' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'create_inquiry' : ActorMethod<[bigint, string, string, string], bigint>,
  'create_listing' : ActorMethod<[Listing], bigint>,
  'delete_listing' : ActorMethod<[bigint], undefined>,
  'getAllAvailableListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getListingCount' : ActorMethod<[], bigint>,
  'getListingInquiries' : ActorMethod<[bigint], Array<Inquiry>>,
  'getListings' : ActorMethod<
    [bigint, bigint, [] | [ListingFilters]],
    ListingsResult
  >,
  'getUserInquiries' : ActorMethod<[Principal], Array<Inquiry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'update_inquiry' : ActorMethod<[bigint, InquiryStatus], undefined>,
  'update_listing' : ActorMethod<[bigint, Listing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];