/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ListingsResult {
    listings: Array<Listing>;
    totalCount: bigint;
}
export type Time = bigint;
export interface Listing {
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    owner: Principal;
    createdAt: Time;
    description: string;
    amenities: Array<string>;
    listingType: ListingType;
    updatedAt: Time;
    currency: string;
    address: Address;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
}
export interface ListingFilters {
    propertyType?: PropertyType;
    city?: string;
    minBedrooms?: bigint;
    maxPrice?: bigint;
    listingType?: ListingType;
    searchText?: string;
    minPrice?: bigint;
}
export interface Inquiry {
    id: bigint;
    status: InquiryStatus;
    requester: Principal;
    endDate: string;
    listingId: bigint;
    createdAt: Time;
    updatedAt: Time;
    message: string;
    startDate: string;
}
export interface UserProfile {
    name: string;
}
export interface Address {
    street?: string;
    city: string;
    neighborhood?: string;
}
export enum InquiryStatus {
    cancelled = "cancelled",
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum ListingStatus {
    rented = "rented",
    sold = "sold",
    available = "available",
    temporarilyUnavailable = "temporarilyUnavailable"
}
export enum ListingType {
    rent = "rent",
    sale = "sale"
}
export enum PropertyType {
    studio = "studio",
    house = "house",
    other = "other",
    land = "land",
    apartment = "apartment"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    create_inquiry(listingId: bigint, startDate: string, endDate: string, message: string): Promise<bigint>;
    create_listing(listing: Listing): Promise<bigint>;
    delete_listing(id: bigint): Promise<void>;
    getAllAvailableListings(): Promise<Array<Listing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListing(id: bigint): Promise<Listing | null>;
    getListingCount(): Promise<bigint>;
    getListingInquiries(listingId: bigint): Promise<Array<Inquiry>>;
    getListings(pageSize: bigint, pageNumber: bigint, filters: ListingFilters | null): Promise<ListingsResult>;
    getUserInquiries(user: Principal): Promise<Array<Inquiry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    update_inquiry(inquiryId: bigint, newStatus: InquiryStatus): Promise<void>;
    update_listing(id: bigint, updated: Listing): Promise<void>;
}
import type { Address as _Address, Inquiry as _Inquiry, InquiryStatus as _InquiryStatus, Listing as _Listing, ListingFilters as _ListingFilters, ListingStatus as _ListingStatus, ListingType as _ListingType, ListingsResult as _ListingsResult, PropertyType as _PropertyType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async create_inquiry(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.create_inquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_inquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async create_listing(arg0: Listing): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.create_listing(to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_listing(to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async delete_listing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.delete_listing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delete_listing(arg0);
            return result;
        }
    }
    async getAllAvailableListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableListings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableListings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingCount();
            return result;
        }
    }
    async getListingInquiries(arg0: bigint): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingInquiries(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingInquiries(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(arg0: bigint, arg1: bigint, arg2: ListingFilters | null): Promise<ListingsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings(arg0, arg1, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ListingsResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings(arg0, arg1, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ListingsResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserInquiries(arg0: Principal): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInquiries(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInquiries(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async update_inquiry(arg0: bigint, arg1: InquiryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_inquiry(arg0, to_candid_InquiryStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_inquiry(arg0, to_candid_InquiryStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async update_listing(arg0: bigint, arg1: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_listing(arg0, to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_listing(arg0, to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Address_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ListingType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingType): ListingType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ListingsResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingsResult): ListingsResult {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : from_candid_Listing_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    owner: Principal;
    createdAt: _Time;
    description: string;
    amenities: Array<string>;
    listingType: _ListingType;
    updatedAt: _Time;
    currency: string;
    address: _Address;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
}): {
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    owner: Principal;
    createdAt: Time;
    description: string;
    amenities: Array<string>;
    listingType: ListingType;
    updatedAt: Time;
    currency: string;
    address: Address;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_PropertyType_n18(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        owner: value.owner,
        createdAt: value.createdAt,
        description: value.description,
        amenities: value.amenities,
        listingType: from_candid_ListingType_n20(_uploadFile, _downloadFile, value.listingType),
        updatedAt: value.updatedAt,
        currency: value.currency,
        address: from_candid_Address_n22(_uploadFile, _downloadFile, value.address),
        areaSqm: value.areaSqm,
        bathrooms: value.bathrooms,
        price: value.price,
        photos: value.photos
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street: [] | [string];
    city: string;
    neighborhood: [] | [string];
}): {
    street?: string;
    city: string;
    neighborhood?: string;
} {
    return {
        street: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.street)),
        city: value.city,
        neighborhood: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.neighborhood))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InquiryStatus;
    requester: Principal;
    endDate: string;
    listingId: bigint;
    createdAt: _Time;
    updatedAt: _Time;
    message: string;
    startDate: string;
}): {
    id: bigint;
    status: InquiryStatus;
    requester: Principal;
    endDate: string;
    listingId: bigint;
    createdAt: Time;
    updatedAt: Time;
    message: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n32(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        endDate: value.endDate,
        listingId: value.listingId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        message: value.message,
        startDate: value.startDate
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listings: Array<_Listing>;
    totalCount: bigint;
}): {
    listings: Array<Listing>;
    totalCount: bigint;
} {
    return {
        listings: from_candid_vec_n13(_uploadFile, _downloadFile, value.listings),
        totalCount: value.totalCount
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    sold: null;
} | {
    available: null;
} | {
    temporarilyUnavailable: null;
}): ListingStatus {
    return "rented" in value ? ListingStatus.rented : "sold" in value ? ListingStatus.sold : "available" in value ? ListingStatus.available : "temporarilyUnavailable" in value ? ListingStatus.temporarilyUnavailable : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studio: null;
} | {
    house: null;
} | {
    other: null;
} | {
    land: null;
} | {
    apartment: null;
}): PropertyType {
    return "studio" in value ? PropertyType.studio : "house" in value ? PropertyType.house : "other" in value ? PropertyType.other : "land" in value ? PropertyType.land : "apartment" in value ? PropertyType.apartment : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rent: null;
} | {
    sale: null;
}): ListingType {
    return "rent" in value ? ListingType.rent : "sale" in value ? ListingType.sale : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): InquiryStatus {
    return "cancelled" in value ? InquiryStatus.cancelled : "pending" in value ? InquiryStatus.pending : "rejected" in value ? InquiryStatus.rejected : "accepted" in value ? InquiryStatus.accepted : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n30(_uploadFile, _downloadFile, x));
}
function to_candid_Address_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Address): _Address {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_ListingFilters_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilters): _ListingFilters {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ListingType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): _ListingType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Listing_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): _Listing {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilters | null): [] | [_ListingFilters] {
    return value === null ? candid_none() : candid_some(to_candid_ListingFilters_n35(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street?: string;
    city: string;
    neighborhood?: string;
}): {
    street: [] | [string];
    city: string;
    neighborhood: [] | [string];
} {
    return {
        street: value.street ? candid_some(value.street) : candid_none(),
        city: value.city,
        neighborhood: value.neighborhood ? candid_some(value.neighborhood) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType?: PropertyType;
    city?: string;
    minBedrooms?: bigint;
    maxPrice?: bigint;
    listingType?: ListingType;
    searchText?: string;
    minPrice?: bigint;
}): {
    propertyType: [] | [_PropertyType];
    city: [] | [string];
    minBedrooms: [] | [bigint];
    maxPrice: [] | [bigint];
    listingType: [] | [_ListingType];
    searchText: [] | [string];
    minPrice: [] | [bigint];
} {
    return {
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n7(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        minBedrooms: value.minBedrooms ? candid_some(value.minBedrooms) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        listingType: value.listingType ? candid_some(to_candid_ListingType_n9(_uploadFile, _downloadFile, value.listingType)) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    owner: Principal;
    createdAt: Time;
    description: string;
    amenities: Array<string>;
    listingType: ListingType;
    updatedAt: Time;
    currency: string;
    address: Address;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
}): {
    id: bigint;
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    owner: Principal;
    createdAt: _Time;
    description: string;
    amenities: Array<string>;
    listingType: _ListingType;
    updatedAt: _Time;
    currency: string;
    address: _Address;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_ListingStatus_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: to_candid_PropertyType_n7(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        owner: value.owner,
        createdAt: value.createdAt,
        description: value.description,
        amenities: value.amenities,
        listingType: to_candid_ListingType_n9(_uploadFile, _downloadFile, value.listingType),
        updatedAt: value.updatedAt,
        currency: value.currency,
        address: to_candid_Address_n11(_uploadFile, _downloadFile, value.address),
        areaSqm: value.areaSqm,
        bathrooms: value.bathrooms,
        price: value.price,
        photos: value.photos
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): {
    rent: null;
} | {
    sale: null;
} {
    return value == ListingType.rent ? {
        rent: null
    } : value == ListingType.sale ? {
        sale: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == InquiryStatus.cancelled ? {
        cancelled: null
    } : value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.rejected ? {
        rejected: null
    } : value == InquiryStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    rented: null;
} | {
    sold: null;
} | {
    available: null;
} | {
    temporarilyUnavailable: null;
} {
    return value == ListingStatus.rented ? {
        rented: null
    } : value == ListingStatus.sold ? {
        sold: null
    } : value == ListingStatus.available ? {
        available: null
    } : value == ListingStatus.temporarilyUnavailable ? {
        temporarilyUnavailable: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    studio: null;
} | {
    house: null;
} | {
    other: null;
} | {
    land: null;
} | {
    apartment: null;
} {
    return value == PropertyType.studio ? {
        studio: null
    } : value == PropertyType.house ? {
        house: null
    } : value == PropertyType.other ? {
        other: null
    } : value == PropertyType.land ? {
        land: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
